In [1]:
import numpy as np



In [2]:
arr = np.array([12,45,78,69,21])

print(arr)

[12 45 78 69 21]


In [3]:
type(arr)

numpy.ndarray

In [4]:
print(np.__version__)

1.20.1


In [9]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(arr1.ndim)

2


In [12]:
arr2= np.array([1,2,3,4,6], ndmin=5)

print(arr2)


[[[[[1 2 3 4 6]]]]]


In [14]:
print(arr2.ndim)

5


In [16]:
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[7,8,9],[4,8,3],[1,5,90]]])

print(arr3)
print(type(arr3))
print(arr3.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 7  8  9]
  [ 4  8  3]
  [ 1  5 90]]]
<class 'numpy.ndarray'>
3


In [17]:
print(arr[0])

12


In [18]:
arr[0] + arr[1]

57

In [20]:
print(arr1[0,1])

2


In [6]:
import numpy as np


arr = np.array([1,2,3,4,5,6,7])


print(arr[1:3])

[2 3]


In [7]:
print(arr[0:4:2])

[1 3]


In [8]:
print(arr[::2])

[1 3 5 7]


In [11]:
print(arr[0::2])

[1 3 5 7]


In [12]:
type(arr)

numpy.ndarray

In [13]:
print(arr.dtype)

int32


In [14]:
newarr = arr.astype("S")

In [15]:
print(newarr)

[b'1' b'2' b'3' b'4' b'5' b'6' b'7']


#newarr.dtype

In [3]:
import numpy as np

arr = np.array([1,2,3,45,6])

new = arr.copy()
new1 = arr.view()
arr[1] = 45

print(arr)
print(new)
print(new1)

[ 1 45  3 45  6]
[ 1  2  3 45  6]
[ 1 45  3 45  6]


In [4]:
print(arr.base)


None


In [5]:
print(new.base)


None


In [6]:
print(new1.base)

[ 1 45  3 45  6]


In [7]:
print(arr.shape)

(5,)


In [8]:
arr.ndim


1

In [13]:
x = arr.reshape(5,1)

print(arr.reshape(5,1))

[[ 1]
 [45]
 [ 3]
 [45]
 [ 6]]


In [14]:
x.ndim

2

In [15]:
x.dtype

dtype('int32')

In [16]:
for x in arr:
    print(x)

1
45
3
45
6


In [17]:
for x in np.nditer(arr):
    print(x)

1
45
3
45
6


In [33]:
arr1 = np.array([[4,5,6,7],[1,2,3,7]])


for x in np.nditer(arr1):
    print(x)

4
5
6
7
1
2
3
7


In [62]:
for y in np.nditer(arr1):
         result = y**2
         print(result)

16
25
36
49
1
4
9
49


In [7]:
import numpy as np

arr1 = np.array([[1,2,3],[7,5,3]])
arr2 = np.array([[4,5,6],[1,5,9]])

arr3 = np.concatenate((arr1,arr2), axis = 1)
print(arr3)

[[1 2 3 4 5 6]
 [7 5 3 1 5 9]]


In [11]:
arr4 = np.stack((arr1,arr2),axis=1)
print(arr4)

[[[1 2 3]
  [4 5 6]]

 [[7 5 3]
  [1 5 9]]]


In [14]:
arr5= np.vstack((arr1,arr2))
print(arr5)


[[1 2 3]
 [7 5 3]
 [4 5 6]
 [1 5 9]]


In [18]:
arr6=np.dstack((arr1,arr2))
print(arr6)

[[[1 4]
  [2 5]
  [3 6]]

 [[7 1]
  [5 5]
  [3 9]]]


In [19]:
arr7 = np.array_split(arr1, 3)
print(arr7)

[array([[1, 2, 3]]), array([[7, 5, 3]]), array([], shape=(0, 3), dtype=int32)]


In [24]:
arr8 = np.hsplit(arr1, 3)
print(arr8)


[array([[1],
       [7]]), array([[2],
       [5]]), array([[3],
       [3]])]


#array search

In [28]:
arr = np.array([4,5,6,7,8,1,3,2,9])

x = np.where(arr == 1)
print(x)

(array([5], dtype=int64),)


In [33]:
y = np.where(arr%2 == 1)


print(y)

(array([1, 3, 5, 6, 8], dtype=int64),)


In [39]:
z = np.searchsorted(arr, 2)
print(z)

0


In [41]:
q=np.sort(arr)
print(q)

[1 2 3 4 5 6 7 8 9]


In [43]:
print(q.base)

None


In [44]:
print(q.ndim)

1


In [45]:
print(q.shape)

(9,)


In [49]:
print(q.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# filtering arrays

In [55]:
arr = np.array([10,45,86,23,69,78,43])

x = [True,False,True,False,True,False,True]

newarr = arr[x]

print(newarr)
print(x)
print(arr)

[10 86 69 43]
[True, False, True, False, True, False, True]
[10 45 86 23 69 78 43]


In [59]:
filter_array = []

for item in arr:
    if item > 50:
        filter_array.append(True)
    else:
        filter_array.append(False)
           
newarr = arr[filter_array]

print(filter_array)
print(newarr)

[False, False, True, False, True, True, False]
[86 69 78]


In [60]:
filterdarr = arr >= 25

newar = arr[filterdarr]

print(newar)

[45 86 69 78 43]


In [61]:
def filterd_arr(array):
    for x in arr:
        if x > 50:
            print(True)
        else:
            print(False)
            
            
filterd_arr(arr)
            

False
False
True
False
True
True
False


In [65]:
filtered_arr = arr % 2 != 1

newarr1 = arr[filtered_arr]

print(newarr1)
print(filtered_arr)

[10 86 78]
[ True False  True False False  True False]
